### ISSUE TITLE
Order of constants in Elo class constructor

### ISSUE THREAD

**Issue by p1mps** [Jleagle/elo-score-calculator#1]
Hello!

I was wondering, is it possible to switch the order of the Elo constants, Elo::WIN and Elo::LOST in the Elo class constructor or it's not a valid call and the first constant has always to be the WIN one?

Thanks

**Comment by Jleagle** [comment]
`__construct($ratingA, $ratingB, $scoreA, $scoreB, $kFactor = 16)`

The first param can be win or lose, it just needs to match up with player 1. The same for the second param, except for player 2. In the same way as param 3 is for player 1 and param 4 is for player 2.

Hope this helps.
